### ISSUE TITLE
High DPI support on Windows 10

### ISSUE THREAD

**Issue by IvanAlekseev** [FrancoisSchnell/GPicSync#9]
Hello,
Thanks for a great tool.
Is there any chance that you can add high DPI support for windows 10?
As far as I understand dependencies update may solve the issue

**Comment by metadirective** [comment]
Hello,
Thanks for letting me know ; I haven't a high DPI screen and wasn't aware of this.
I plan to revisit the app this summer since WxPython is compatible with Python 3 now.
In the meantime there's maybe a trick (not sure if it works with GPicSync),
http://pocketnow.com/2016/01/25/hidpi-scalling-in-windows-10

**Comment by IvanAlekseev** [comment]
It is not that bad that I have to use workarounds. The app is usable, only text is pixelated
